name: Auto review action
description: Automatically adds reviewers to pull request and merges them to help you to deal with thunk-like workflows

inputs:
  scheme-file:
    description: File with review scheme
    required: true
    default: ''
  mode:
    description: Reviewers setting mode — single (assigns one reviewer at once) or multiple
    required: false
    default: multiple
  type:
    description: Reviewers scheme file type - centralized (with top-level repository map) or distributed (PR authors at the top level)
    required: false
    default: centralized

runs:
  using: node12
  main: app/index.js
